pipeline {
    agent any
//  parameters {
//   credentials credentialType: 'com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl', defaultValue: 'AWS_CREDS_AUTOMATION_ACCT', name: 'AWS_AUTOMATION_ACCOUNT_CRED', required: false
// }

    environment {
        PATH = "${PATH}:${getTerraformPath()}:${getAnsiblePath()}}"
    }
    stages{

         stage('Initial Stage') {
              steps {
                script {
                def userInput = input(id: 'confirm', message: 'Start Pipeline?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Start Pipeline', name: 'confirm'] ])
             }
           }
        }

         stage('Packer AMI Build'){
             steps {
                //  withCredentials([string(credentialsId: 'MGT_ACC_AWS_ACCESS_KEY', variable: 'MGT_ACC_AWS_ACCESS_KEY'), string(credentialsId: 'MGT_ACCT_SECRET_KEY', variable: 'MGT_ACCT_SECRET_KEY')]){
                 sh """
                 cd images
                 current_ami_id=$(grep "ami-stack-*" image.pkr.hcl |awk '{print  '$3'}'|sed  s/\"//g |awk -F - '{print '$3'}')
                 old_ami_id='$current_ami_id'
                 let current_ami_id++
                 sed -i 's/'$old_ami_id'/'$current_ami_id'/' image.pkr.hcl
                 export PACKER_LOG=1
                 export PACKER_LOG_PATH=$WORKSPACE/packer.log
                 /usr/bin/packer build -force image.pkr.hcl 
                 """
                 }
        //  }
         }

       
        
    }
}

 def getTerraformPath(){
        def tfHome= tool name: 'terraform-14', type: 'terraform'
        return tfHome
    }

 def getAnsiblePath(){
        def AnsibleHome= tool name: 'Ansible', type: 'org.jenkinsci.plugins.ansible.AnsibleInstallation'
        return AnsibleHome
    }

// def getPackerPath(){
//        def PackerHome= tool name: 'Packer', type: 'biz.neustar.jenkins.plugins.packer.PackerInstallation'
//     }